name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  darwin:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        swift: ["6.0"]
        os: [macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build and Test Swift Package
        uses: ./.github/actions/ci

  linux:
    name: Linux
    strategy:
      matrix:
        swift: ["6.0"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: CI
        uses: ./.github/actions/ci
